name: Deploy to Hostinger

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install SSH key
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.HOSTINGER_SSH_KEY }}
        ssh-passphrase: ${{ secrets.HOSTINGER_SSH_PASSPHRASE }}

    - name: Deploy to Hostinger
      run: |
        ssh -p 65002 u891050743@82.25.106.109 'bash -s' < ./deploy.sh